name: build-and-push

on: push

env:
  IMAGE_FQDN: docker.io/ireshmm/unison

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - { ocaml: "4.14.0", unison: "2.53.2" }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker IO
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_IO_USERNAME }}
          password: ${{ secrets.DOCKER_IO_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ env.IMAGE_FQDN }}:${{ matrix.versions.unison }}-${{ matrix.versions.ocaml }}
          build-args: |
            OCAML_VERSION=${{ matrix.versions.ocaml }}
            UNISON_VERSION=${{ matrix.versions.unison }}
      # push only on main
      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_FQDN }}:${{ matrix.versions.unison }}-${{ matrix.versions.ocaml }}
          build-args: |
            OCAML_VERSION=${{ matrix.versions.ocaml }}
            UNISON_VERSION=${{ matrix.versions.unison }}
